# Jean Park, jejupark@ucsc.edu
# $Id: Makefile,v 1.3 2017-04-10 22:18:24-07 - - $

# CMPS104a Spring - William Mackey
# Makefile for proj1 

# This Makefile was written by William Mackey and modified by Jean Park.

# Bug Log
# - missing '/' at beginning of directory

EXECBIN   = p1test
MAINCSRC   = p1test
NOINCLUDE = ci clean spotless
NEEDINCL  = ${filter ${NOINCLUDE}, ${MAKECMDGOALS}}

SUFFIX    = cc

CPP       = g++ -g -O0 -Wall -Wextra -std=gnu++11 ${XCFLAGS}

MKDEPS    = g++ -MM -std=gnu++11
GRIND     = valgrind --leak-check=full --show-reachable=yes

MODULES   = pfm rbfm
HDRSRC    = ${MODULES:=.h}
CPPSRC    = ${MODULES:=.${SUFFIX}} ${MAINCSRC}.${SUFFIX}

ALLCSRC   = ${CPPSRC} 
OBJECTS   = ${ALLCSRC:.${SUFFIX}=.o}

MODSRC    = ${foreach MOD, ${MODULES}, ${MOD}.h ${MOD}.${SUFFIX}}
MISCSRC   = ${filter-out ${MODSRC}, ${HDRSRC} ${CPPSRC}}
ALLSRC    = README Makefile ${MODSRC} ${MISCSRC} 

PRETESTS  = 00_exist.t 02_destroy.t
TESTINS   = ${wildcard test*.in}

LISTSRC   = ${ALLSRC} ${DEPSFILE}


all : ${EXECBIN} 

${EXECBIN} : ${OBJECTS}
	${CPP} -o${EXECBIN} ${OBJECTS}
	

%.o : %.${SUFFIX}
                  ## $< means first prerequisite (aka param/argument)
	${CPP} -c $<

ci : ${ALLSRC} ${TESTINS}
	- cpplint.py.perl ${CPPSRC}
	cid + ${ALLSRC} ${TESTINS} test?.inh

clean :
	- rm ${OBJECTS} ${DEPSFILE} core 
	- rm ${foreach test, ${TESTINS:.in=}, \
		${patsubst %, ${test}.%, out err log}}

spotless : clean
	- rm ${EXECBIN}

deps : ${ALLCSRC}
	@ echo "# ${DEPSFILE} created `date` by ${MAKE}" >${DEPSFILE}
	${MKDEPS} ${ALLCSRC} >>${DEPSFILE}

${DEPSFILE} :
	@ touch ${DEPSFILE}
	${MAKE} --no-print-directory deps


tests : ${EXECBIN}
	touch ${TESTINS}
	make --no-print-directory ${TESTINS:.in=.out}

%.out %.err : %.in
	${GRIND} --log-file=$*.log ${EXECTEST} $< 1>$*.out 2>$*.err; \
	echo EXIT STATUS = $$? >>$*.log

again :
	gmake --no-print-directory spotless deps ci all lis

#--- Added by Jean Park


gitcheck: 
	git status
	echo "git commit -m"
	echo "git gmake push"
check: 
	gmake gitcheck

add:
	git add --all .
	gmake check -i

push:
	git push origin master
	git log

#--- written by Mackey. What does this do?
	
ifeq "${NEEDINCL}" ""
include ${DEPSFILE}
endif

